{
  "scan_metadata": {
    "scan_session_id": "enterprise_scan_20250705_104204_cbf84b54",
    "scan_start_time": "2025-07-05T05:12:04.305880+00:00",
    "scan_end_time": "2025-07-05T05:13:05.709690+00:00",
    "scan_duration_seconds": 61.40381
  },
  "analysis_session_id": "error_analysis_20250705_104305_04458940",
  "analysis_timestamp": "2025-07-05T05:13:05.809653+00:00",
  "total_errors": 61,
  "errors": [
    {
      "Account": "588989875114",
      "Region": "ap-northeast-1",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.323725+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-2",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.327486+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-3",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.340467+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-south-1",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.344700+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-southeast-1",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.349680+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-southeast-2",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.355101+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ca-central-1",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.358068+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-central-1",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.363391+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-north-1",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.367244+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-west-1",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.371181+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-west-2",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.374878+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-west-3",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.378313+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "sa-east-1",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.382488+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-east-1",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.386875+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-east-2",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.390292+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-west-1",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.393888+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-west-2",
      "Service": "cloudwatch",
      "Function": "list_metrics",
      "ErrorType": "parameter_validation",
      "ErrorMessage": "Parameter validation failed:\nUnknown parameter in input: \"MaxRecords\", must be one of: Namespace, MetricName, Dimensions, NextToken, RecentlyActive, IncludeLinkedAccounts, OwningAccount",
      "Timestamp": "2025-07-05T05:12:11.397529+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-west-3",
      "Service": "comprehend",
      "Function": "list_document_classifiers",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidRequestException) when calling the ListDocumentClassifiers operation: UNSUPPORTED_OPERATION: This operation is not supported in this region",
      "Timestamp": "2025-07-05T05:12:12.735396+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-west-1",
      "Service": "comprehend",
      "Function": "list_document_classifiers",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidRequestException) when calling the ListDocumentClassifiers operation: UNSUPPORTED_OPERATION: This operation is not supported in this region",
      "Timestamp": "2025-07-05T05:12:13.444286+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-3",
      "Service": "comprehend",
      "Function": "list_document_classifiers",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://comprehend.ap-northeast-3.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:13.570524+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "sa-east-1",
      "Service": "comprehend",
      "Function": "list_document_classifiers",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidRequestException) when calling the ListDocumentClassifiers operation: UNSUPPORTED_OPERATION: This operation is not supported in this region",
      "Timestamp": "2025-07-05T05:12:13.676605+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-south-1",
      "Service": "connect",
      "Function": "list_instances",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidRequestException) when calling the ListInstances operation: None",
      "Timestamp": "2025-07-05T05:12:13.904832+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-north-1",
      "Service": "comprehend",
      "Function": "list_document_classifiers",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://comprehend.eu-north-1.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:15.031775+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-east-2",
      "Service": "connect",
      "Function": "list_instances",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://connect.us-east-2.amazonaws.com/instance\"",
      "Timestamp": "2025-07-05T05:12:16.629689+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-west-1",
      "Service": "connect",
      "Function": "list_instances",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://connect.eu-west-1.amazonaws.com/instance\"",
      "Timestamp": "2025-07-05T05:12:17.149159+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "sa-east-1",
      "Service": "connect",
      "Function": "list_instances",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://connect.sa-east-1.amazonaws.com/instance\"",
      "Timestamp": "2025-07-05T05:12:17.373404+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-west-3",
      "Service": "connect",
      "Function": "list_instances",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://connect.eu-west-3.amazonaws.com/instance\"",
      "Timestamp": "2025-07-05T05:12:18.073440+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-west-1",
      "Service": "connect",
      "Function": "list_instances",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://connect.us-west-1.amazonaws.com/instance\"",
      "Timestamp": "2025-07-05T05:12:18.591726+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-north-1",
      "Service": "connect",
      "Function": "list_instances",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://connect.eu-north-1.amazonaws.com/instance\"",
      "Timestamp": "2025-07-05T05:12:19.948585+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "global",
      "Service": "globalaccelerator",
      "Function": "list_accelerators",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://globalaccelerator.us-east-1.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:33.675126+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-3",
      "Service": "rekognition",
      "Function": "list_collections",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://rekognition.ap-northeast-3.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:45.853568+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-south-1",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:47.088058+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "sa-east-1",
      "Service": "rekognition",
      "Function": "list_collections",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://rekognition.sa-east-1.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:47.189497+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-2",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:47.322850+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-3",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:47.362791+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-southeast-2",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:47.481167+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-1",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:47.491748+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-central-1",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:47.750773+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-north-1",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:47.871437+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-west-2",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:47.961084+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-west-1",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:47.968603+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-north-1",
      "Service": "rekognition",
      "Function": "list_collections",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://rekognition.eu-north-1.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:47.974575+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-west-3",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:48.023586+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-west-3",
      "Service": "rekognition",
      "Function": "list_collections",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://rekognition.eu-west-3.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:48.042555+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ca-central-1",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:48.193053+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-west-1",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:48.320901+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-west-2",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:48.498974+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-east-2",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:48.510293+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "sa-east-1",
      "Service": "securityhub",
      "Function": "get_enabled_standards",
      "ErrorType": "unknown",
      "ErrorMessage": "An error occurred (InvalidAccessException) when calling the GetEnabledStandards operation: Account 588989875114 is not subscribed to AWS Security Hub",
      "Timestamp": "2025-07-05T05:12:48.658786+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "global",
      "Service": "shield",
      "Function": "list_protections",
      "ErrorType": "resource_not_found",
      "ErrorMessage": "An error occurred (ResourceNotFoundException) when calling the ListProtections operation: The subscription does not exist.",
      "Timestamp": "2025-07-05T05:12:48.941047+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-north-1",
      "Service": "textract",
      "Function": "list_adapters",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://textract.eu-north-1.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:56.238002+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-1",
      "Service": "textract",
      "Function": "list_adapters",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://textract.ap-northeast-1.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:56.573180+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-3",
      "Service": "transcribe",
      "Function": "list_transcription_jobs",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://transcribe.ap-northeast-3.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:56.793479+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-3",
      "Service": "translate",
      "Function": "list_text_translation_jobs",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://translate.ap-northeast-3.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:58.229558+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-3",
      "Service": "textract",
      "Function": "list_adapters",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://textract.ap-northeast-3.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:58.537872+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "sa-east-1",
      "Service": "textract",
      "Function": "list_adapters",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://textract.sa-east-1.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:58.681659+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "sa-east-1",
      "Service": "translate",
      "Function": "list_text_translation_jobs",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://translate.sa-east-1.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:12:59.412592+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-west-1",
      "Service": "workspaces",
      "Function": "describe_workspaces",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://workspaces.us-west-1.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:13:02.747314+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "ap-northeast-3",
      "Service": "workspaces",
      "Function": "describe_workspaces",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://workspaces.ap-northeast-3.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:13:02.753219+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "eu-north-1",
      "Service": "workspaces",
      "Function": "describe_workspaces",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://workspaces.eu-north-1.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:13:04.049245+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    },
    {
      "Account": "588989875114",
      "Region": "us-east-2",
      "Service": "workspaces",
      "Function": "describe_workspaces",
      "ErrorType": "endpoint_connection_error",
      "ErrorMessage": "Could not connect to the endpoint URL: \"https://workspaces.us-east-2.amazonaws.com/\"",
      "Timestamp": "2025-07-05T05:13:05.708446+00:00",
      "ScanSessionId": "enterprise_scan_20250705_104204_cbf84b54"
    }
  ]
}